# -*- coding: utf-8 -*-
"""password generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cNqXriNQmIh2fM1OhgMJ0jl9xPgJZ705
"""

import secrets
import string
import random

for _ in range(10):
    length = random.randint(16, 32)
    chars = string.ascii_uppercase + string.ascii_lowercase + string.digits + string.punctuation
    print(''.join(secrets.choice(chars) for _ in range(length)))